//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseOfMusic.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarehouseOfMusic.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на добавить блок.
        /// </summary>
        public static string AppBarAddSample {
            get {
                return ResourceManager.GetString("AppBarAddSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на добавить дорожку.
        /// </summary>
        public static string AppBarAddTrack {
            get {
                return ResourceManager.GetString("AppBarAddTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на создать проект.
        /// </summary>
        public static string AppBarCreateProject {
            get {
                return ResourceManager.GetString("AppBarCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на справка.
        /// </summary>
        public static string AppBarHelp {
            get {
                return ResourceManager.GetString("AppBarHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на длительность ноты.
        /// </summary>
        public static string AppBarNoteDuration {
            get {
                return ResourceManager.GetString("AppBarNoteDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пауза.
        /// </summary>
        public static string AppBarPause {
            get {
                return ResourceManager.GetString("AppBarPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на играть.
        /// </summary>
        public static string AppBarPlay {
            get {
                return ResourceManager.GetString("AppBarPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на продолжить.
        /// </summary>
        public static string AppBarResume {
            get {
                return ResourceManager.GetString("AppBarResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на остановить.
        /// </summary>
        public static string AppBarStop {
            get {
                return ResourceManager.GetString("AppBarStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СОЗДАТЬ ПРОЕКТ.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на удалить.
        /// </summary>
        public static string DeleteContextMenu {
            get {
                return ResourceManager.GetString("DeleteContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дублировать.
        /// </summary>
        public static string DuplicateContextMenu {
            get {
                return ResourceManager.GetString("DuplicateContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, задайте имя..
        /// </summary>
        public static string ErrorEmptyName {
            get {
                return ResourceManager.GetString("ErrorEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание новой музыкальной композиции..
        /// </summary>
        public static string HelpMain2 {
            get {
                return ResourceManager.GetString("HelpMain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переход к редактированию композиции - нажмите на композициию из списка..
        /// </summary>
        public static string HelpMain3 {
            get {
                return ResourceManager.GetString("HelpMain3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переименование или удаление композиции - удерживайте нажатие на композиции из списка..
        /// </summary>
        public static string HelpMain4 {
            get {
                return ResourceManager.GetString("HelpMain4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление новой дорожки к музыкальной композиции..
        /// </summary>
        public static string HelpProject1 {
            get {
                return ResourceManager.GetString("HelpProject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переименование или удаление дорожки - удерживайте нажатие на дорожке из списка..
        /// </summary>
        public static string HelpProject10 {
            get {
                return ResourceManager.GetString("HelpProject10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Воспроизведение с начала музыкальной композиции с учётом настроек режимов воспроизведения дорожек..
        /// </summary>
        public static string HelpProject2 {
            get {
                return ResourceManager.GetString("HelpProject2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановка воспроизведения композиции на текущем моменте..
        /// </summary>
        public static string HelpProject3 {
            get {
                return ResourceManager.GetString("HelpProject3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжение воспроизведения композиции с момента остановки..
        /// </summary>
        public static string HelpProject4 {
            get {
                return ResourceManager.GetString("HelpProject4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прекращение воспроизведения композиции..
        /// </summary>
        public static string HelpProject5 {
            get {
                return ResourceManager.GetString("HelpProject5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение темпа - нажмите на блок с названием &quot;темп&quot;..
        /// </summary>
        public static string HelpProject6 {
            get {
                return ResourceManager.GetString("HelpProject6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор инструмента - нажмите кнопку следующую за названием дорожки, на которой отображается название текущего выбранного инструмента..
        /// </summary>
        public static string HelpProject7 {
            get {
                return ResourceManager.GetString("HelpProject7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение режима воспроизведения - в правой части экрана для нужной дорожки выберите режим. s - сольный. m - без звука..
        /// </summary>
        public static string HelpProject8 {
            get {
                return ResourceManager.GetString("HelpProject8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переход к редактированию дорожки - нажмите на дорожку из списка..
        /// </summary>
        public static string HelpProject9 {
            get {
                return ResourceManager.GetString("HelpProject9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение длительности ноты..
        /// </summary>
        public static string HelpSample1 {
            get {
                return ResourceManager.GetString("HelpSample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление ноты - нажатие на сетку..
        /// </summary>
        public static string HelpSample2 {
            get {
                return ResourceManager.GetString("HelpSample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление ноты -двойное нажатие на удаляемую ноту..
        /// </summary>
        public static string HelpSample3 {
            get {
                return ResourceManager.GetString("HelpSample3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление нового блока в конец дорожки..
        /// </summary>
        public static string HelpTrack1 {
            get {
                return ResourceManager.GetString("HelpTrack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переключение между дорожками..
        /// </summary>
        public static string HelpTrack2 {
            get {
                return ResourceManager.GetString("HelpTrack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещение блока - удерживайте нажатие на стрелках около нужного блока..
        /// </summary>
        public static string HelpTrack3 {
            get {
                return ResourceManager.GetString("HelpTrack3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Воспроизведение дорожки с определенного блока - нажмите треугольник на нужном блоке..
        /// </summary>
        public static string HelpTrack4 {
            get {
                return ResourceManager.GetString("HelpTrack4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дублирование, переименование и удаление блока - удерживайте нажатие на дорожке из списка..
        /// </summary>
        public static string HelpTrack5 {
            get {
                return ResourceManager.GetString("HelpTrack5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переход к редактированию блока - нажмите на блок из списка..
        /// </summary>
        public static string HelpTrack6 {
            get {
                return ResourceManager.GetString("HelpTrack6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на главная.
        /// </summary>
        public static string MainString {
            get {
                return ResourceManager.GetString("MainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите значение от 30 до 240..
        /// </summary>
        public static string MessageChangeTempo {
            get {
                return ResourceManager.GetString("MessageChangeTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите длительность ноты..
        /// </summary>
        public static string MessageChoseNoteSize {
            get {
                return ResourceManager.GetString("MessageChoseNoteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите количество тактов в добавляемом блоке..
        /// </summary>
        public static string MessageChoseSampleSize {
            get {
                return ResourceManager.GetString("MessageChoseSampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить проект.
        /// </summary>
        public static string MessageDeleteProject {
            get {
                return ResourceManager.GetString("MessageDeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить блок.
        /// </summary>
        public static string MessageDeleteSample {
            get {
                return ResourceManager.GetString("MessageDeleteSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить дорожку.
        /// </summary>
        public static string MessageDeleteTrack {
            get {
                return ResourceManager.GetString("MessageDeleteTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не подходит!.
        /// </summary>
        public static string MessageIncorrectValue {
            get {
                return ResourceManager.GetString("MessageIncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на композиция.
        /// </summary>
        public static string ProjectString {
            get {
                return ResourceManager.GetString("ProjectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на переименовать.
        /// </summary>
        public static string RenameContextMenu {
            get {
                return ResourceManager.GetString("RenameContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПЕРЕИМЕНОВАТЬ ПРОЕКТ.
        /// </summary>
        public static string RenameProject {
            get {
                return ResourceManager.GetString("RenameProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПЕРЕИМЕНОВАТЬ БЛОК.
        /// </summary>
        public static string RenameSample {
            get {
                return ResourceManager.GetString("RenameSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПЕРЕИМЕНОВАТЬ ДОРОЖКУ.
        /// </summary>
        public static string RenameTrack {
            get {
                return ResourceManager.GetString("RenameTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru-RU.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на блок.
        /// </summary>
        public static string SampleString {
            get {
                return ResourceManager.GetString("SampleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВЫБРАТЬ ИНСТРУМЕНТ.
        /// </summary>
        public static string SelectInstrument {
            get {
                return ResourceManager.GetString("SelectInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТАКТ.
        /// </summary>
        public static string TactString {
            get {
                return ResourceManager.GetString("TactString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на темп.
        /// </summary>
        public static string TextBlockTextTempo {
            get {
                return ResourceManager.GetString("TextBlockTextTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИЗМЕНИТЬ ТЕМП.
        /// </summary>
        public static string TitleChangeTempo {
            get {
                return ResourceManager.GetString("TitleChangeTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дорожка.
        /// </summary>
        public static string TrackString {
            get {
                return ResourceManager.GetString("TrackString", resourceCulture);
            }
        }
    }
}
