//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseOfMusic.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarehouseOfMusic.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на добавить блок.
        /// </summary>
        public static string AppBarAddSample {
            get {
                return ResourceManager.GetString("AppBarAddSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на добавить дорожку.
        /// </summary>
        public static string AppBarAddTrack {
            get {
                return ResourceManager.GetString("AppBarAddTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на создать проект.
        /// </summary>
        public static string AppBarCreateProject {
            get {
                return ResourceManager.GetString("AppBarCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на справка.
        /// </summary>
        public static string AppBarHelp {
            get {
                return ResourceManager.GetString("AppBarHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пауза.
        /// </summary>
        public static string AppBarPause {
            get {
                return ResourceManager.GetString("AppBarPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на играть.
        /// </summary>
        public static string AppBarPlay {
            get {
                return ResourceManager.GetString("AppBarPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на продолжить.
        /// </summary>
        public static string AppBarResume {
            get {
                return ResourceManager.GetString("AppBarResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на настройки.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на стоп.
        /// </summary>
        public static string AppBarStop {
            get {
                return ResourceManager.GetString("AppBarStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРИМЕНИТЬ.
        /// </summary>
        public static string ApplySettingsButtonContent {
            get {
                return ResourceManager.GetString("ApplySettingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СОЗДАТЬ ПРОЕКТ.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удобная.
        /// </summary>
        public static string CustomThemeListBoxItem {
            get {
                return ResourceManager.GetString("CustomThemeListBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Темная.
        /// </summary>
        public static string DarkThemeListBoxItem {
            get {
                return ResourceManager.GetString("DarkThemeListBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на удалить.
        /// </summary>
        public static string DeleteContextMenu {
            get {
                return ResourceManager.GetString("DeleteContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, задайте имя..
        /// </summary>
        public static string ErrorEmptyName {
            get {
                return ResourceManager.GetString("ErrorEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на язык.
        /// </summary>
        public static string LanguageTextBlockText {
            get {
                return ResourceManager.GetString("LanguageTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светлая.
        /// </summary>
        public static string LightThemeListBoxItem {
            get {
                return ResourceManager.GetString("LightThemeListBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите значение от 30 до 240..
        /// </summary>
        public static string MessageChangeTempo {
            get {
                return ResourceManager.GetString("MessageChangeTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить проект?.
        /// </summary>
        public static string MessageDeleteProject {
            get {
                return ResourceManager.GetString("MessageDeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить блок?.
        /// </summary>
        public static string MessageDeleteSample {
            get {
                return ResourceManager.GetString("MessageDeleteSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить дорожку?.
        /// </summary>
        public static string MessageDeleteTrack {
            get {
                return ResourceManager.GetString("MessageDeleteTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не подходит!.
        /// </summary>
        public static string MessageIncorrectValue {
            get {
                return ResourceManager.GetString("MessageIncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проект.
        /// </summary>
        public static string ProjectString {
            get {
                return ResourceManager.GetString("ProjectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на переименовать.
        /// </summary>
        public static string RenameContextMenu {
            get {
                return ResourceManager.GetString("RenameContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПЕРЕИМЕНОВАТЬ ПРОЕКТ.
        /// </summary>
        public static string RenameProject {
            get {
                return ResourceManager.GetString("RenameProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПЕРЕИМЕНОВАТЬ БЛОК.
        /// </summary>
        public static string RenameSample {
            get {
                return ResourceManager.GetString("RenameSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПЕРЕИМЕНОВАТЬ ДОРОЖКУ.
        /// </summary>
        public static string RenameTrack {
            get {
                return ResourceManager.GetString("RenameTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru-RU.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НАСТРОЙКИ.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТАКТ.
        /// </summary>
        public static string TactString {
            get {
                return ResourceManager.GetString("TactString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на темп.
        /// </summary>
        public static string TextBlockTextTempo {
            get {
                return ResourceManager.GetString("TextBlockTextTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на тема.
        /// </summary>
        public static string ThemeTextBlockText {
            get {
                return ResourceManager.GetString("ThemeTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИЗМЕНИТЬ ТЕМП.
        /// </summary>
        public static string TitleChangeTempo {
            get {
                return ResourceManager.GetString("TitleChangeTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дорожка.
        /// </summary>
        public static string TrackString {
            get {
                return ResourceManager.GetString("TrackString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на громкость.
        /// </summary>
        public static string VolumeTextBlockText {
            get {
                return ResourceManager.GetString("VolumeTextBlockText", resourceCulture);
            }
        }
    }
}
